-- 코드를 작성해주세요
SELECT A.ITEM_ID, B.ITEM_NAME, B.RARITY
FROM ITEM_TREE AS A
JOIN ITEM_INFO AS B
ON A.ITEM_ID = B.ITEM_ID
JOIN ITEM_INFO C
ON A.PARENT_ITEM_ID = C.ITEM_ID
WHERE C.RARITY = 'RARE'
ORDER BY A.ITEM_ID DESC